global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'python-producer'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'python-consumer'
    static_configs:
      - targets: ['host.docker.internal:8001']